version: "1"
rules:
  - base: template
    upstream: ublue-os:template
    mergeMethod: hardreset
    mergeUnstable: false
  - base: live
    upstream: noahdotpy:template
    mergeMethod: rebase
    mergeUnstable: false
