# https://universal-blue.org/tinker/modules/rpm-ostree/
type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/eclipseo/espanso/repo/fedora-%OS_VERSION%/eclipseo-espanso-fedora-%OS_VERSION%.repo
install:
  - chromium
  - piper
  - zsh
