# https://universal-blue.org/tinker/modules/rpm-ostree/
type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
install:
  - cliphist
  - hyprland-contrib
  - hyprland-git
  - hyprland-plugins-git
  - hyprlock
  - hyprnome
  - hyprpaper
  - hyprpicker
  - hyprshot
  - kitty
  - nwg-clipman
  - nwg-look
  - qt5ct
  - qt6ct
  - swaylock
  - waybar
  - wlogout
  - xdg-desktop-portal-hyprland

