# image will be published to ghcr.io/<user>/<name>
name: bluefin
# description will be included in the image's metadata
description: This is my personal OS image based on ublue-os/bluefin (AMD/Intel).

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - from-file: modules/packages.yml
  - from-file: modules/files.yml
  - from-file: modules/scripts.yml
