# image will be published to ghcr.io/<user>/<name>
name: mybazzite
# description will be included in the image's metadata
description: This is my personal OS image based on ublue-os/bazzite-gnome running on a Lenovo Ideapad S145-14IWL with an Intel i3.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
modules:
  - from-file: packages.yml
  - from-file: bling.yml
  - from-file: files.yml
  - from-file: scripts.yml
