block-flatpak-networking:
  users_affected:
  - noah
  apps:
  - com.google.Chrome
user-networking:
  users:
    noah:
      mode: allow
  schedules:
    schedule1:
      days_allowed: wednesday
      time_start: 8:30
      time_end: 15:00
tightener-config:
  approved-updates:
    # field - regex: value - regex
    # allow updating field `user-networking.users.<ANY USER>.mode` with value `disallow`
    ^user-networking\.users\.[^.]+\.mode$: ^disallow$
  approved-appends:
    # field - regex
    # allow appending to block-flatpak-networking.apps
    - ^block-flatpak-networking\.apps$
