kill-plasma-windows:
  - description: "Block Tor Browser"
    title: "Tor Browser"
block-sites:
  - tails.net
  - torproject.org
  - proxyium.com
flatpak-app-networking:
  allow:
    # Tools
    - com.bitwarden.desktop
    - com.github.GradienceTeam.Gradience
    - com.github.GradienceTeam.Gradience.Devel
    - com.mattjakeman.ExtensionManager
    - com.warlordsoftwares.formatlab
    - dev.Cogitri.Health
    - io.github.flattool.Warehouse
    - io.missioncenter.MissionCenter
    - md.obsidian.Obsidian
    - org.libreoffice.LibreOffice
    - org.onlyoffice.desktopeditors
    - xyz.ketok.Speedtest
    
    # Dev
    - com.github.marhkb.Pods
    - com.vscodium.codium
    - io.github.dvlv.boxbuddyrs

    # GNOME Apps
    - dev.bragefuglseth.Keypunch
    - org.gnome.Calendar
    - org.gnome.Podcasts
    - org.gnome.Weather
    - org.gnome.clocks
    - page.kramo.Cartridges

    # Internet
    - com.transmissionbt.Transmission
    - de.haeckerfelix.Fragments
    - de.haeckerfelix.Shortwave
    - io.gitlab.news_flash.NewsFlash
    - us.zoom.Zoom
  block:
    # Browsers
    - com.brave.Browser
    - com.ghostery.browser
    - com.google.Chrome
    - com.google.ChromeDev
    - com.microsoft.Edge
    - com.microsoft.EdgeDev
    - com.opera.Opera
    - com.vivaldi.Vivaldi
    - eu.betterbird.Betterbird
    - io.github.ungoogled_software.ungoogled_chromium
    - io.github.zen_browser.zen
    - io.gitlab.librewolf-community
    - net.mullvad.MullvadBrowser
    - net.waterfox.waterfox
    - one.ablaze.floorp
    - org.chromium.Chromium
    - org.gnome.Epiphany
    - org.kde.falkon
    - org.midori_browser.Midori
    - org.mozilla.firefox
    - org.torproject.torbrowser-launcher
    - re.sonny.Tangram
    - ru.yandex.Browser
