tightener-config:
  approved-commands:
    - ^config \.flatpak-app-networking.block \+= \["[^"']*\.[^"']*\.[^"']*"\]$ # config '.block-flatpak-networking.apps += "com.google.Chrome"'
    - ^config \.block-sites \+= \["[^"']*"\]$ # config '.block-sites += "youtube.com"'
