tightener:
  approved-commands:
    - ^config \.block-sites \+= \["[^"']*"\]$
    - ^config \.flatpak-app-networking\.allow-only -= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.flatpak-app-networking\.block \+= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.networking\.mode = "block"$
    - ^group remove [^\s]* wheel$
    - ^make_file_immutable .*$
    - ^config \.tightener\.delay \+= [0-9]*$

    # examples: (in form of a list of args - how tightener would get it)
    # ["config" ".block-sites += ["youtube.com""]
    # ["config", ".flatpak-app-networking.allow-only -= ["org.signal.Signal""]
    # ["config", ".flatpak-app-networking.block += ["org.signal.Signal""]
    # ["config", ".networking.mode = "block""]
    # ["group", "remove", "john", "wheel"]
    # ["make_file_immutable", "file.txt"]
    # ["config", ".tightener.delay += 10"]
