tightener-config:
  approved-commands:
    - ^config \.disconnect-flatpak-apps \+= "[^"']*\.[^"']*\.[^"']*"$ # config '.block-flatpak-networking.apps += "com.google.Chrome"'
    - ^config \.block-sites \+= "[^"']*"$ # config '.block-sites += "youtube.com"'
