tightener:
  approved-commands:
    - ^config \.block-networking = false$
    - ^config \.block-sites \+= \["[^"']*"\]$
    - ^config \.flatpak-app-networking\.allow-only -= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.flatpak-app-networking\.block \+= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.flatpak-app-networking\.block-otherwise = true$
    # TODO: Test if the below actually works properly
    # - ^config \.process-killing\.allow-always\."[^"']*" = "TODO: Clean this up (it was removed by tightener)"$
    - ^config \.process-killing\.block \+= \["[^"']*"\]$
    - ^config \.tightener\.delay \+= [0-9]*$
    - ^config \.tightener\.delay-enabled = false$
    - ^group remove [^\s]* wheel$
    - ^make_file_immutable .*$

    # examples: (in form of a list of args - how tightener would get it)
    # [ 'config', '.block-sites += ["youtube.com"]' ]
    # [ 'config', '.flatpak-app-networking.allow-only -= ["org.signal.Signal"]' ]
    # [ 'config', '.flatpak-app-networking.block += ["org.signal.Signal"]' ]
    # [ 'config', '.networking.mode = "block"' ]
    # [ 'config', '.process-killing.allow-always."/home/noah/.local/share/activitywatch/aw-qt" = "TODO: Clean this up (it was removed by tightener)"' ]
    # [ 'config', '.process-killing.block += ["/home/noah/"]' ]
    # [ 'config', '.tightener.delay += 10' ]
    # [ 'group', 'remove', 'john', 'wheel' ]
    # [ 'make_file_immutable', 'file.txt' ]
