name: bazzite
on:
  schedule:
    - cron: "00 5 * * 2,5" # 5:00 UTC every Tuesday and Thursday
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - bazzite-gnome.yml
          - bazzite-plasma.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.5
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
