name: Build `git` frequency
on:
  schedule:
    - cron: "00 07 * * 0" # 07:00 UTC every Sunday
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"
    branches-ignore:
      - 'dependabot**'
      - 'compiler'

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - images/kavon-hypr/regular/current/kavon-hypr--current-git.yml
          - images/kavon-hypr/regular/previous/kavon-hypr--previous-git.yml

          - images/kavon/dx/current/kavon-dx--current-git.yml
          - images/kavon/dx/previous/kavon-dx--previous-git.yml
          - images/kavon/regular/current/kavon--current-git.yml
          - images/kavon/regular/previous/kavon--previous-git.yml

          - images/silvara-hypr/dx/current/silvara-hypr-dx--current-git.yml
          - images/silvara-hypr/dx/previous/silvara-hypr-dx--previous-git.yml
          - images/silvara-hypr/regular/current/silvara-hypr--current-git.yml
          - images/silvara-hypr/regular/previous/silvara-hypr--previous-git.yml
          
          - images/silvara/dx/current/silvara-dx--current-git.yml
          - images/silvara/dx/previous/silvara-dx--previous-git.yml
          - images/silvara/regular/current/silvara--current-git.yml
          - images/silvara/regular/previous/silvara--previous-git.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.7
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
