name: GTS Stream (weekly, git)
on:
  schedule:
    - cron: "00 07 * * 0" # 07:00 UTC every Sunday
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          # - images/aurora/dx/gts/aurora-dx--gts-git.yml
          # - images/aurora/regular/gts/aurora--gts-git.yml
          - images/bluefin/dx/gts/bluefin-dx--gts-git.yml
          - images/bluefin/regular/gts/bluefin--gts-git.yml
          # - images/horizon-aurora/dx/gts/horizon-aurora-dx--gts-git.yml
          # - images/horizon-aurora/regular/gts/horizon-aurora--gts-git.yml
          - images/horizon-bluefin/dx/gts/horizon-bluefin-dx--gts-git.yml
          - images/horizon-bluefin/regular/gts/horizon-bluefin--gts-git.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.7
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
