name: Stable Stream (daily, git)
on:
  schedule:
    - cron: "00 06 * * *" # 06:00 UTC daily
  push:
    paths-ignore:
      - '/toolboxes/**'
      - "**.md"

  pull_request:
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - images/aurora/dx/stable/aurora-dx--stable-daily-git.yml
          - images/aurora/regular/stable/aurora--stable-daily-git.yml
          - images/bluefin/dx/stable/bluefin-dx--stable-daily-git.yml
          - images/bluefin/regular/stable/bluefin--stable-daily-git.yml
          - images/hyra/dx/stable/hyra-dx--stable-daily-git.yml
          - images/hyra/regular/stable/hyra--stable-daily-git.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.7
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
